scheme: sftp
host: example.com
username: user
password: pass
path: path/to/deployment

exclude:
    - .gitignore
    - dandelion.yml
    - folder/

additional:
    - public/css/print.css
    - public/css/screen.css
    - public/js/main.js